SELECT * FROM BABSANG_INFO;

SELECT * FROM USER_INFO;

SELECT * FROM COMMENT_INFO;
DESC BABSANG_INFO;


INSERT INTO BABSANG_INFO (BI_TITLE, BI_CONTENT, BI_MEETINGDAT, BI_MEETINGTIM,
BI_HEADCNT, BI_FDCATEGORY, BI_CLOSED, UI_NUM) VALUES(
'롯데리아뿌실분', '내일 저녁 6시 롯데리아 ㄱㄱ', '2023-05-24', '20:00:00',
6, '버거', FALSE, 2), (
'오늘저녁번개소주팟', '1시간 뒤 미사역시계탑ㄱㄱㄱ', '2023-05-22', '23:00:00',
4, '야식', FALSE, 3)
;

ALTER TABLE BABSANG_INFO MODIFY BI_MEETINGDAT date NOT NULL;
ALTER TABLE BABSANG_INFO MODIFY BI_MEETINGTIM TIME NOT NULL;

ALTER TABLE USER_INFO ADD UI_CREDAT DATETIME NOT NULL DEFAULT NOW();
