SELECT * FROM BOARD_INFO;

UPDATE BOARD_INFO
SET BI_TITLE = CONCAT('아무제목', BI_NUM),
BI_CONTENT = CONCAT('아무내용', BI_NUM);

SELECT BI.*, UI.UI_NAME FROM BOARD_INFO BI, USER_INFO UI WHERE BI.UI_NUM = UI.UI_NUM;
-- 같은 방식
SELECT BI.*, UI.UI_NAME FROM BOARD_INFO BI INNER JOIN USER_INFO UI ON BI.UI_NUM = UI.UI_NUM;