SELECT * FROM BABSANG_INFO;
SELECT * FROM COMMENT_INFO;
SELECT * FROM USER_INFO;

SELECT last_insert_id(BI_NUM) FROM BABSANG_INFO;

INSERT INTO USER_INFO (UI_NICKNAME, UI_PWD, UI_FILEPATH, UI_GENDER, 
UI_AGE, BI_NUM, UI_CREDAT, UI_ID, 
UI_ACTIVE, UI_DEL) VALUES
('관리자', '1111', '/resources/upload/관리자사진.png', 0, 30, 0, NOW(), 'Administer', 0, null);

SELECT * FROM USER_INFO;
SELECT * FROM KAKAO_USER_INFO;
DELETE FROM USER_INFO WHERE UI_NUM = 91;

commit;


