SELECT * FROM MEMBER_TBL_02;

UPDATE MEMBER_TBL_02 SET GRADE = 'A' WHERE CUSTNO = 100007;

DESC MEMBER_TBL_02;

SELECT CUSTNO, CUSTNAME, PHONE, ADDRESS, 
TO_CHAR(JOINDATE,'YYYY-MM-DD') JOINDATE, 
DECODE(GRADE, 'A', 'VIP', 'B', '老馆', 'C', '流盔') GRADE, CITY
FROM MEMBER_TBL_02;

SELECT mb.CUSTNO, mb.CUSTNAME, mb.GRADE, SUM(mo.PRICE) 
FROM MEMBER_TBL_02 mb, MONEY_TBL_02 mo
WHERE mb.CUSTNO = mo.CUSTNO
GROUP BY mb.CUSTNO, mb.CUSTNAME, mb.GRADE
ORDER BY SUM(mo.PRICE) desc;

SELECT mb.CUSTNO, mb.CUSTNAME, DECODE(mb.GRADE, 'A', 'VIP', 'B', '老馆', 'C', '流盔') GRADE, SUM(mo.PRICE) PRICE
FROM MEMBER_TBL_02 mb, MONEY_TBL_02 mo
WHERE mb.CUSTNO = mo.CUSTNO
GROUP BY mb.CUSTNO, mb.CUSTNAME, GRADE
ORDER BY SUM(mo.PRICE) desc;


COMMIT;